export enum AppRouteEnum {
    BASIC = '/',
    BASIC_AUTH = '/auth',
    BASIC_MAIN = '/main',
    AUTH = '/auth/*',
    RESULT = '/result/*',
    MAIN = '/main/*',
    FEEDBACKS = '/feedbacks',
    REGISTRATION = '/auth/registration',
    CONFIRM_EMAIL = '/auth/confirm-email',
    CHANGE_PASSWORD = '/auth/change-password',
    ERROR_LOGIN = '/result/error-login',
    SUCCESS = '/result/success',
    ERROR_USER_EXIST = '/result/error-user-exist',
    ERROR = '/result/error',
    ERROR_CHECK_EMAIL_NO_EXIST = '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL = '/result/error-check-email',
    SUCCESS_CHANGE_PASSWORD = '/result/success-change-password',
    ERROR_CHANGE_PASSWORD = '/result/error-change-password',
}
