export enum DataTestEnum {
    MENU_BUTTON_PROFILE = 'menu-button-profile',
    HEADER_SETTINGS = 'header-settings',

    PROFILE_NAME = 'profile-name',
    PROFILE_SURNAME = 'profile-surname',
    PROFILE_AVATAR = 'profile-avatar',
    PROFILE_EMAIL = 'profile-email',
    PROFILE_BIRTHDAY = 'profile-birthday',
    PROFILE_PASSWORD = 'profile-password',
    PROFILE_REPEAT_PASSWORD = 'profile-repeat-password',
    PROFILE_SUBMIT = 'profile-submit',
    BIG_FILE_ERROR_CLOSE = 'big-file-error-close',
    ALERT = 'alert',

    SETTINGS_BACK = 'settings-back',
    PRO_TARIFF_CARD = 'pro-tariff-card',
    ACTIVATE_TARIFF_BTN = 'activate-tariff-btn',
    TARIFF_TRAININGS = 'tariff-trainings',
    TARIFF_NOTIFICATIONS = 'tariff-notifications',
    TARIFF_THEME = 'tariff-theme',
    TARIFF_TRAININGS_ICON = 'tariff-trainings-icon',
    TARIFF_NOTIFICATIONS_ICON = 'tariff-notifications-icon',
    TARIFF_THEME_ICON = 'tariff-theme-icon',
    TARIFF_SIDER = 'tariff-sider',
    TARIFF_SUBMIT = 'tariff-submit',
    TARIFF_COST = 'tariff-cost',
    TARIFF_MODAL_SUCCESS = 'tariff-modal-success',

    NEW_REVIEW_SUBMIT_BUTTON = 'new-review-submit-button',

    SIDER_SWITCH = 'sider-switch',
    SIDER_SWITCH_MOBILE = 'sider-switch-mobile',

    MODAL_NO_REVIEW = 'modal-no-review',
    MODAL_ERROR_USER_TRAINING_TITLE = 'modal-error-user-training-title',
    MODAL_ERROR_USER_TRAINING_SUBTITLE = 'modal-error-user-training-subtitle',
    MODAL_ERROR_USER_TRAINING_BUTTON = 'modal-error-user-training-button',
    MODAL_ERROR_USER_TRAINING_BUTTON_CLOSE = 'modal-error-user-training-button-close',
    MENU_BUTTON_CALENDAR = 'menu-button-calendar',
    MODAL_CREATE_TRAINING = 'modal-create-training',
    MODAL_CREATE_TRAINING_BUTTON_CLOSE = 'modal-create-training-button-close',
    MODAL_UPDATE_TRAINING_EDIT_BUTTON = 'modal-update-training-edit-button',
    MODAL_CREATE_EXERCISE = 'modal-create-exercise',
    MODAL_CREATE_EXERCISE_SELECT = 'modal-create-exercise-select',
    MODAL_EXERCISE_TRAINING_BUTTON_CLOSE = 'modal-exercise-training-button-close',
    MODAL_DRAWER_RIGHT = 'modal-drawer-right',
    MODAL_DRAWER_RIGHT_BUTTON_CLOSE = 'modal-drawer-right-button-close',
    MODAL_DRAWER_RIGHT_INPUT_EXERCISE = 'modal-drawer-right-input-exercise',
    MODAL_DRAWER_RIGHT_CHECKBOX_EXERCISE = 'modal-drawer-right-checkbox-exercise',
    MODAL_DRAWER_RIGHT_INPUT_APPROACH = 'modal-drawer-right-input-approach',
    MODAL_DRAWER_RIGHT_INPUT_WEIGHT = 'modal-drawer-right-input-weight',
    MODAL_DRAWER_RIGHT_INPUT_QUANTITY = 'modal-drawer-right-input-quantity',

    LOADER = 'loader',

    LOGIN_EMAIL = 'login-email',
    LOGIN_PASSWORD = 'login-password',
    LOGIN_REMEMBER = 'login-remember',
    LOGIN_FORGOT_BUTTON = 'login-forgot-button',
    LOGIN_SUBMIT_BUTTON = 'login-submit-button',

    REGISTRATION_EMAIL = 'registration-email',
    REGISTRATION_PASSWORD = 'registration-password',
    REGISTRATION_CONFIRM_PASSWORD = 'registration-confirm-password',
    REGISTRATION_SUBMIT_BUTTON = 'registration-submit-button',

    CHANGE_PASSWORD = 'change-password',
    CHANGE_CONFIRM_PASSWORD = 'change-confirm-password',
    CHANGE_SUBMIT_BUTTON = 'change-submit-button',

    CONFIRM_EMAIL_VERIFICATION_INPUT = 'verification-input',

    REGISTRATION_ENTER_BUTTON = 'registration-enter-button',
    REGISTRATION_RETRY_BUTTON = 'registration-retry-button',
    REGISTRATION_BACK_BUTTON = 'registration-back-button',
    LOGIN_RETRY_BUTTON = 'login-retry-button',
    CHECK_RETRY_BUTTON = 'check-retry-button',
    CHECK_BACK_BUTTON = 'check-back-button',
    CHANGE_RETRY_BUTTON = 'change-retry-button',
    CHANGE_ENTER_BUTTON = 'change-entry-button',

    SEE_REVIEWS = 'see-reviews',

    WRITE_REVIEW_NOT_SAVED_MODAL = 'write-review-not-saved-modal',

    WRITE_REVIEW = 'write-review',

    ALL_REVIEWS_BUTTON = 'all-reviews-button',
}
